### ISSUE TITLE
Can I use this for faster inference?

### ISSUE THREAD

**Issue by abhimanyu891998** [fabawi/ImageBind-LoRA#9]
Hi @fabawi , thanks for your work on this! I have been experimenting with imageBind for videos, I essentially extract the clips (5 secs), audio and subtitles from a video and I want them all in the same embedding space. I have tried this with the vanilla imagebind implementation on my 3080ti GPU with 24GB memory. However, I am facing an issue where the embedding generation takes too long. For a 8 minute video, it takes 40 minutes to generate the embeddings for video clips, text segments and audio clips (each corresponding to every 5 second segment of the video). 

I was wondering if I could use your implementation to speed up the inference, or if you know of a way to quantize imageBind model to accelerate this process? Or maybe I am doing something wrong, just wanted your advice on it. Thanks again!

**Comment by fabawi** [comment]
We do not provide quantization-aware training, a PR is very much welcome though. You will probably get better help posting this issue on the imagebind repo. Post training dynamic quantization is what you might be looking for, since you wouldn't need to finetune the model and can apply it during inference time
